### ISSUE TITLE
Usage: runStepFunction (openloop)

### ISSUE THREAD

**Issue by formica-multiuso** [blandry/crazyflie-tools#21]
Hi guys,
I'm trying to use your examples script in the openloop directory as a first step, without any result.

Lcm is installed.
The crazyflie is flashed with the firmware in your crazyflie-firmware-2 directory.
simpleclient.py is running (green leds are blink both on the CrazyradioPA and on the Crazyflie).

When I ran the runRampFunction.m in matlab I was expecting some variation on the propeller speed, but nothing happens!

lcm-spy shows correctly a message stream published on the crazyflie_input channel and recognize message's type.

Any idea?

Roberto

**Comment by formica-multiuso** [comment]
I'm trying also to simulate an input form a python script but nothing happens!! :(

simpleclient.py is running with this client options
'''
############################ CLIENT OPTIONS ##########################################
#TXRX_FREQUENCY = 1000.0

STARTUP_NANOKONTROL = False
USE_DRAKE_CONTROLLER = False

SE_LISTEN_TO_VICON = False
SE_VICON_CHANNEL = 'MOCAP#1'
SE_PUBLISH_TO_LCM = True
SE_USE_RPYDOT = True
SE_USE_EKF = True
SE_USE_UKF = False
SE_DELAY_COMP = False

CTRL_INPUT_TYPE = 'omegasqu'
CTRL_LISTEN_TO_LCM = True
CTRL_LISTEN_TO_EXTRA_INPUT = True
CTRL_PUBLISH_TO_LCM = True

CTRL_USE_POSITION_CONTROL = True
######################################################################################
'''

**Comment by blandry** [comment]
For lcm-spy to be able to read the messages the jars that contain their definition needs to be in your class path (lcm-spy is in Java).  It boils down to adding lines like this in your .bashrc:

    export CLASSPATH=$CLASSPATH:(path_to_your_install)/crazyflie-tools/vicon/src/vicon_t.jar
    export CLASSPATH=$CLASSPATH:(path_to_your_install)/crazyflie-tools/lcm/crazyflie_t.jar

I am assuming you installed the lcm types by running the setup.py in the lcm directory.

Also when you connect to the crazyflie does the LED on it eventually turn red? This means it has switched to the offboard control loop (which is what you want).

Let me know if you can now see the lcm-messages and we can take it from there.

**Comment by formica-multiuso** [comment]
lcm-spy is correctly recognizing the messages type, when I publish from my "test" python script.
(crazyflie_extra_input channel)

When I connect from the pc the FRONT-LEFT led turn red for a short period, then keep going on blinking in green (this should mean that is connected).

I did not add the vicon_t.jar, for the moment, because I'm trying to control it in openloop, just for test.

Still no variation of motor's speed.

**Comment by blandry** [comment]
Ok if the firmware was installed properlly the props should react to you moving the quad around, whether or not you are connected to it. 

Now if you are using the onboard controller as well you should be sending input of the type crazyflie_positioninput_t which corresponds to [desired roll, desired pitch, desired yaw, desired omega_x, desired omega_y, desired omega_z, offset thrust]. This isn't overly clear yet because the onboard attitude controller was added more towards the end. So try running the client with these options:

#TXRX_FREQUENCY = 1000.0

STARTUP_NANOKONTROL = False
USE_DRAKE_CONTROLLER = False

SE_LISTEN_TO_VICON = False
SE_VICON_CHANNEL = 'MOCAP#1'
SE_PUBLISH_TO_LCM = True
SE_USE_RPYDOT = True
SE_USE_EKF = True
SE_USE_UKF = False
SE_DELAY_COMP = False

CTRL_INPUT_TYPE = 'omegasqu'
CTRL_LISTEN_TO_LCM = True
CTRL_LISTEN_TO_EXTRA_INPUT = True
CTRL_PUBLISH_TO_LCM = False
CTRL_USE_POSITION_CONTROL = True

Note: The "publish to lcm" should only be used when you run the python controller and want to see the inputs being sent (for sys id purposes for example). Otherwise you might be publishing the input twice.

And this script

    import lcm
    from crazyflie_t import crazyflie_positioninput_t

    msg = crazyflie_positioninput_t()
    msg.timestamp = 0
    msg.input = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 20.0]

    lc = lcm.LCM()
    while True:
        lc.publish("crazyflie_input", msg.encode())

**Comment by formica-multiuso** [comment]
no way
following your hints there's no results. :(

(the props react properly while moving the crazyflie: the firmware seems ok)

**Comment by formica-multiuso** [comment]
I added some debug printing lines inside the subscriber handlers I suppose to listen for 'crazyflie_input' (controller.py, line 186) but it seems don't recieving any message.

**Comment by formica-multiuso** [comment]
UP! 
Any idea?

I'm desperate. :D

**Comment by formica-multiuso** [comment]
Maybe, in order to communicate, I have to reprogram my crazyradioPA usb dongle with a custom firmware?

**Comment by blandry** [comment]
If you have an old usb dongle then yes you might want to update to the new firmware. We haven't changed anything from the one bitcraze distributes but I think they did change some of it between the two crazyflie versions. Everything you need should be in our submodule (instruction in the readme).

I am currently out of the lab so I cannot test the script right now... but you can try adding a pose in the while loop of your script. It is possible there are just too many messages being sent.

    import time 
    while True:
        lc.publish("crazyflie_input", msg.encode()) 
        time.sleep(.5)

**Comment by blandry** [comment]
@peteflorence do you think you could run the script in a few comments above and see if it get the CF going?

**Comment by peteflorence** [comment]
@blandry sure I can do. Won't be able to until next Tuesday though due to
travel

**Comment by formica-multiuso** [comment]
Sleep instruction added, as @blandry suggested.
Still not going. :(

**Comment by blandry** [comment]
Maybe one of the threads isn't booting because there is a package missing and the import errors are not getting through. Can you put a bunch of print statements _connected function of simpleclient and see if it gets through the whole thing?

**Comment by blandry** [comment]
Doing the same thing in _transmitter_thread would be usefull too.

**Comment by formica-multiuso** [comment]
I added two print statements in _connected and _transmitter_thread, but I don't see them.

simpleclient remains hanged up printing "Connecting to radio://0/...", but seemed connected (green led keep on blinking)
So, until now I was using a different crazyflie-clients-python (a multiradio branch) but now, using the fork that you included in your repo (which branch do you suggest?) the green led blink for a short period and then it dies.

**Comment by blandry** [comment]
Ah you definitly need to use our fork (master branch) of the crazyflie-clients-python. We modified it so that we can take direct control of the read and write to the usb. It allows us to skip some queues.

The LED should definitly only be red if the offboard controller is running properly:
![screenshot from 2015-07-01 12 46 46](https://cloud.githubusercontent.com/assets/2207326/8460035/4483939a-1fef-11e5-91e7-508f02d9ef59.png)

Also you might want to use the second line here if you changed the channel on the firmware:

    client = SimpleClient('radio://0/80/250K')
    #client = SimpleClient(available[0][0])

**Comment by peteflorence** [comment]
Nice debugging @blandry

**Comment by formica-multiuso** [comment]
@blandry @peteflorence 
NO WAY also using your modified cflib.
I forgot that I had this problem
    Scanning interfaces for Crazyflies...
    Crazyflies found:
    radio://0/80/250K
    Connecting to radio://0/80/250K
    No handlers could be found for logger "cflib.crazyflie.toccache"

I (apparently) solved that issue adding:
    import logging
    logging.basicConfig(level=logging.ERROR)

but maybe that its a wrong solution and the program hangs up exactly there.
Waiting for your solution

-rob

**Comment by formica-multiuso** [comment]
So, if I use your firmware (done) and your cfclient, should I see the IMU horizon moving?
It's seems that there is a communication error... horizon totally fixed, maybe no data from the IMU.

**Comment by blandry** [comment]
Hey Robert,
So we stopped using the GUI a while back. The horizon instrument that you are refering to uses the logging process which we turned off onboard to maximize the time spent doing stabilization and comm. So we only use the cflib in that package. Sorry for the confusion, you're definitly using the bleeding edge of our tools.

-Install our custom cflib by going into crazyflie-clients-python

    sudo python setup.py install

You might have to remove a previous install if you have one (pip uninstall).

-install the state estimator.

    cd estimation
    sudo python setup.py install

-install the lcm message types (which you already seem to have done - lcm-spy reconginzes them)
-flash the firmware (which seems to be working 100% since the attitude controller reacts)
-Start the crazyflie
-Start the simple client

    python simpleclient.py

You should then see the LED's on the quad flash for a bit and turn red
-Start your test script in another process

    python test.py

You can check if you are getting the IMU messages back through the option

    SE_PUBLISH_TO_LCM = True

It should publish the state estimates via LCM. If you want the raw IMU messages you can uncomment the lines 135 to 142 in simple client

    # msg = crazyflie_imu_t()
    # msg.omegax = imu_reading[0]
    # msg.omegay = imu_reading[1]
    # msg.omegaz = imu_reading[2]
    # msg.alphax = imu_reading[3]
    # msg.alphay = imu_reading[4] 
    # msg.alphaz = imu_reading[5]
    # imu_lc.publish('crazyflie_imu', msg.encode())

If this doesn't help it might be worth getting on setting up a gchat hangout or something similar. Although unlikely it might be the USB package that isn't working. Also the logging error you are getting is normal and shouldn't affect the anything.

**Comment by formica-multiuso** [comment]
no way at all!
I think that is a USB issue;

>dmesg
 [  287.256334] usb 1-2: reset full-speed USB device number 3 using xhci_hcd
[  287.385182] xhci_hcd 0000:00:14.0: xHCI xhci_drop_endpoint called with disabled ep ffff8800d9406948
[  287.385187] xhci_hcd 0000:00:14.0: xHCI xhci_drop_endpoint called with disabled ep ffff8800d9406900

Reproduced on another computer there is a similar output, there referred to the ehci driver

**Comment by formica-multiuso** [comment]
@blandry I think that a gchat session could be a good idea.
If you can I will really appreciate it.

(I just added you on gchat)

**Comment by blandry** [comment]
Ok. Just emailed the address you have listed on your profile.

**Comment by blandry** [comment]
So this turned out to be a usb driver issue as expected. Bitcraze had code to handle this sort of things that we didn't port over. For now replacing these three methods in simpleclient.py should fix it, but a more permanant change should be made. Creating a task about it.

    def _write_usb(self, dataout):
        try:
            self._dev_handle.bulkWrite(1, dataout, 0)
        except usb.USBError:
            pass

    def _write_read_usb(self, dataout):
        datain = None
        try:
            self._dev_handle.bulkWrite(1, dataout, 0)
            datain = self._dev_handle.bulkRead(0x81, 64, 5)
        except usb.USBError:
            pass
        return datain

    def _send_vendor_setup(self, request, value, index, data):
        self._dev_handle.controlMsg(usb.TYPE_VENDOR, request, data, value=value,
                          index=index, timeout=1000)
